### ISSUE TITLE
the data was not provided, could you upload it? many thanks

### ISSUE THREAD

**Issue by meichen1129** [peter-herman/modeling_complex_trade_network_patterns#1]
{ gdp.data <- read.dta("P:\\Documents\\Working Papers\\Data Various\\World Bank GDPs.dta")

**Comment by peter-herman** [comment]
This appears to be an old piece of code that is not actually used anywhere in the analysis. I removed it as well as a few other unnecessary functions in that file. The GDP data that is used is taken from the CEPII Gravity data by a different function.

**Comment by meichen1129** [comment]
got it, I have checked the files of function and found that the data of gdp was not used in the analysis, thanks a lot!
